openapi: 3.0.1
info:
  title: 默认模块
  description: ''
  version: 1.0.0
tags: []
paths:
  /v3/user/points/stat:
    get:
      summary: 个人中心-积分
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: ''
          example: login-access-token-example
          schema:
            type: string
            default: login-access-token-example
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security: []
components:
  schemas: {}
  responses: {}
  securitySchemes: {}
servers: []
security: []
