openapi: 3.0.1
info:
  title: 默认模块
  description: ''
  version: 1.0.0
tags: []
paths:
  /v3/user/getorders:
    post:
      summary: 个人中心-订单列表
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: ''
          example: login-access-token-example
          schema:
            type: string
            default: login-access-token-example
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                keywords:
                  type: string
                pageindex:
                  type: integer
                pagesize:
                  type: integer
                status:
                  type: string
                withdetail:
                  type: boolean
              required:
                - keywords
                - pageindex
                - pagesize
                - status
                - withdetail
            example:
              keywords: ''
              pageindex: 1
              pagesize: 10
              status: All
              withdetail: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  responses: {}
  securitySchemes: {}
servers: []
security: []
